# Generated by Django 2.0.1 on 2018-01-29 04:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=64, unique=True)),
                ('passwd', models.CharField(max_length=64)),
                ('head', models.ImageField(upload_to='')),
                ('age', models.IntegerField()),
                ('sex', models.IntegerField()),
                ('pid', models.IntegerField(default=1)),
            ],
        ),
    ]
